id: example_feature_extension
name: Example Feature Extension
description: This is an example feature extension
version: 1.0.0
authors: Soufiane Oualil <https://github.com/sooualil>, Ahmed Bargady <https://github.com/AhmedCoolProjects>
license: BSD

requirements: requirements.txt

log:
  dir: ./logs
  level: INFO

channels:
  input:
    files: [./pcap/2022-11-17-Bumblebee-infection-traffic.pcap]
    interfaces: []
  publish: [feature-channel]
